repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: libs/
      - id: end-of-file-fixer
        files: libs/
      - id: check-yaml
        files: libs/
      - id: check-added-large-files
        files: libs/

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: libs/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: libs/
        args:
          - "--profile=black"

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        files: libs/
        args:
        - --remove-all-unused-imports
        - --recursive
        - --remove-unused-variables
        - --in-place
        additional_dependencies: [flake8]