version: "3.8"

services:
  db:
    image: postgres # this uses the 'latest' version
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234 # only do this in development
      POSTGRES_DB: llmstudio
    volumes:
      - ./db:/var/lib/postgresql/data # save data between restarts
    ports:
      - 5556:5432 # binds port 5556 on your computer to the postgres port!
